coreruleset/modsecurity-crs-docker

3.3-apache/Dockerfile, 3.3-nginx/Dockerfile, src/docker-entrypoint.sh
Replaced python with sed in entrypoint script.
Fixes: #2
I did some tests to make sure the content of the file is the same as the previous version.
These are the commands that I ran:
Build the image on the old branch with python:
```console
docker build src -f 3.3-nginx/Dockerfile --tag owasp/modsecurity-crs:old
```
```console
docker run -ti -e PARANOIA=11 \
-e EXECUTING_PARANOIA=11 \
-e ENFORCE_BODYPROC_URLENCODED=11 \
-e ANOMALYIN=11 \
-e ANOMALYOUT=11 \
-e ALLOWED_METHODS=11 \
-e ALLOWED_REQUEST_CONTENT_TYPE=11 \
-e ALLOWED_REQUEST_CONTENT_TYPE_CHARSET=11 \
-e ALLOWED_HTTP_VERSIONS=11 \
-e RESTRICTED_EXTENSIONS=11 \
-e STATIC_EXTENSIONS=11 \
-e MAX_NUM_ARGS=11 \
-e ARG_NAME_LENGTH=11 \
-e ARG_LENGTH=11 \
-e TOTAL_ARG_LENGTH=11 \
-e MAX_FILE_SIZE=11 \
-e COMBINED_FILE_SIZES=11 \
-e …
```
=> Replace python with sed

3.3-nginx/Dockerfile, 3.3-nginx/conf.d/default.conf, 3.3-nginx/docker-entrypoint.sh, 3.3-nginx/nginx.conf, README.md, src/etc/modsecurity.d/modsecurity-override.conf
Added the following env variables to the Nginx image:
* NGINX_KEEPALIVE_TIMEOUT
* ERRORLOG
* LOGLEVEL
* USER
* PORT
* SERVERNAME
* WORKER_CONNECTIONS
* MODSEC_RULE_ENGINE
* MODSEC_REQ_BODY_ACCESS
* MODSEC_REQ_BODY_LIMIT
* MODSEC_REQ_BODY_NOFILES_LIMIT
* MODSEC_RESP_BODY_ACCESS
* MODSEC_RESP_BODY_LIMIT
* MODSEC_PCRE_MATCH_LIMIT
* MODSEC_PCRE_MATCH_LIMIT_RECURSION
Since the Nginx does not recognise the env variables in the conf files, I used `envsubst` in the entrypoint script.
=> Add env variables to nginx

3.3-apache/Dockerfile, 3.3-nginx/Dockerfile, REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf, RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
from archived 
https://github.com/SpiderLabs/owasp-modsecurity-crs
to
https://github.com/coreruleset/coreruleset
I did a local test build of both Dockerfiles which finished without error.
Repo change seems to work correctly:
```
Initialized empty Git repository in /opt/owasp-crs/.git/
From https://github.com/coreruleset/coreruleset
* branch            v3.3/dev   -> FETCH_HEAD
* [new branch]      v3.3/dev   -> origin/v3.3/dev
Switched to a new branch 'v3.3/dev'
Branch 'v3.3/dev' set up to track remote branch 'v3.3/dev' from 'origin'.
```
should partly resolve #14
=> Update repo references

3.3-nginx/docker-entrypoint.sh, 3.3-nginx/nginx.conf
After https://github.com/coreruleset/modsecurity-docker/commit/214041c580b83d38f8cb4fc2ea8e8a45eeaf9722, nginx image cannot start anymore:
```
$ docker run -p 80:80 -ti -e PROXY=1 -e LOGLEVEL=warn --rm owasp/modsecurity-crs:3.3-nginx
2020/08/07 11:28:36 [emerg] 1#1: duplicate "log_format" name "main" in /etc/nginx/conf.d/logging.conf:3
nginx: [emerg] duplicate "log_format" name "main" in /etc/nginx/conf.d/logging.conf:3
```
These changes should fix the issues.
=> 3.3-nginx broken after configuration changes in base image

.github/workflows/buildimage.yml
Fixes docker push to the hub. We are not using the tag latest, so we need to specify tags accordingly.
=> fix(ci): fixes docker push without specific tag

.github/workflows/buildimage.yml
Try to use `--all-tags` instead of naming each tag.
=> fix(ci): use all tags in docker push

.github/workflows/dockerhub-description.yml
Had to create additional secrets because dockerhub api does not support tokens yet.
=> fix(ci): update matching secrets per action documentation

README.md, src/opt/modsecurity/activate-rules.sh
This variable is being used by the CRS testing framework (taken from the regression test docs):
Requirements
============
There are Three requirements for running the OWASP CRS regressions.
1. You must have ModSecurity specify the location of your error.log, this is done in the config.py file
2. ModSecurity must be in DetectionOnly (or anomaly scoring) mode
3. You must disable IP blocking based on previous events
Note: The test suite compares timezones -- if your test machine and your host machine are in different timezones this can cause bad results
To accomplish 2. and 3. you may use the following rule in your setup.conf:
```
SecAction "id:900005,\
phase:1,\
nolog,\
pass,\
ctl:ruleEngine=DetectionOnly,\ …
```
=> feat(utf8): add variable for validating utf8

.github/workflows/buildimage.yml, .github/workflows/verifyimage.yml, Makefile, README.md
Updates base ruleset after security release 3.3.2.
=> fix(security): include 3.3.2 release by default

apache/Dockerfile
This fixes curl not finding github certificates for downloading crs.
=> fix(armv7): update certificates before using curl

src/opt/modsecurity/activate-rules.sh
Corrects variable name in substitution.
Fixes https://github.com/coreruleset/modsecurity-crs-docker/issues/69
=> fix: correct variable name

README.md, apache/conf/extra/httpd-modsecurity.conf
SERVER_NAME and SERVER_ADMIN were used inconsistently in this image and the base. Fix depends on https://github.com/coreruleset/modsecurity-docker/pull/123.
=> fix(apache): use SERVER_ variables from base image

apache/Dockerfile, apache/Dockerfile-alpine, apache/docker-entrypoint.sh
The latest build on dockerhub of the Apache image does not have an ENTRYPOINT directive [1]. 
That leads to `activate-rules.sh` not being sourced and env variables like `ALLOWED_METHODS` not being written to `crs-setup.conf` and therefore not applied. (I noticed ALLOWED_METHOD related messages in my logs a couple of days ago)
Not sure which (parent) image set the ENTRYPOINT before. Hence I introduce it here and not in the parent image to avoid that problem in the future.
[1] https://hub.docker.com/layers/modsecurity-crs/owasp/modsecurity-crs/3.3.2-apache/images/sha256-56461eaca2a6120d10a1ec8406b76be72cdc1ce2db2ba17503f9c820cfe0912c?context=explore
=> Fix missing ENTRYPOINT in Apache flavor

README.md, src/opt/modsecurity/activate-rules.sh
Fixes #39.
- Adds `MANUAL_MODE` so the `crs-setup.conf` file can be mounted as a volume.
=> feat(mode): adds MANUAL_MODE for crs configuration

.github/workflows/buildimage.yml, .github/workflows/verifyimage.yml, README.md, apache/Dockerfile, apache/Dockerfile-alpine, docker-bake.hcl, nginx/Dockerfile, nginx/Dockerfile-alpine
- tags are based on build date using YYYYMMDDHHMM
This is the same as https://github.com/coreruleset/modsecurity-docker/pull/140 for this repository.
Fixes #67.
=> feat(ci): use unique tags when pushing to hub

README.md
I used the example code shown in README.md but it does not work. it was made by syntax errors. I fixed it.
- Add `-p` option to specify port instead of image
- Add `\` to connect lines
fail -> success to run image as a container.
When you run the command, you can see this error.
```console
Unable to find image '80:80' locally
docker: Error response from daemon: pull access denied for 80, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
This is caused by Docker recognize `80:80` as image name.
```
docker run -dti 80:80 --rm \
-e PARANOIA=1 \
-e EXECUTING_PARANOIA=2 \
-e ENFORCE_BODYPROC_URLENCODED=1 \
...
```
When you fix it, next you will see this error:
```
"docker run" requires at least 1 argument. …
```
=> Fix run example

apache/Dockerfile
Use current modsecurity base image, to enable environment variable `PROXY_ERROR_OVERRIDE` from the [latest release](https://github.com/coreruleset/modsecurity-docker/pull/162)
=> Use current modsecurity base image in apache Dockerfile

README.md, apache/Dockerfile, apache/Dockerfile-alpine, apache/docker-entrypoint.sh, nginx/Dockerfile, nginx/Dockerfile-alpine, src/opt/modsecurity/activate-plugins.sh, src/opt/modsecurity/activate-rules.sh
- moves plugin activation to its own activation file
- adds a new variable to completely disable plugins, even if files are present
=> feat(plugins): move activation to its own file

README.md
This PR is going to fix the CRS docker command as https://github.com/coreruleset/modsecurity-crs-docker#crs-versions
```sh
❯ docker run -p 80:80 -ti -e PARANOIA=4 -v ./rules:/opt/owasp-crs/rules:ro --rm owasp/modsecurity-crs
docker: Error response from daemon: create ./rules: "./rules" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
See 'docker run --help'.
```
Works well in my macOS 13.2 with Docker desktop version 4.16.2 (95914)
```sh
docker run -p 80:80 -ti -e PARANOIA=4 -v rules:/opt/owasp-crs/rules:ro --rm owasp/modsecurity-crs
```
=> Fix crs version docker command

nginx/Dockerfile, nginx/Dockerfile-alpine
ModSecurity depends on libpcre3-dev. libpcre++-dev also depends on libpcre3-dev.
So we can just use libpcre3-dev to avoid redundancy.
=> Use libpcre3 instead of libpcre++ to reduce build time and image size.

src/bin/healthcheck
The default curl user agent triggers CRS. The healthcheck now uses a custom user agent to prevent this.
=> fix: prevent healthcheck from triggering rules

README.md
The default value of SSL_ENGINE was never correct in the readme.
=> docs: default value of SSL_ENGINE is `on`

apache/Dockerfile, apache/Dockerfile-alpine, nginx/Dockerfile-alpine
- update Lua to 5.3 (the highest supported version)
- add missing Lua packages (httpd comes with Lua 5.2 installed, but if we want 5.3 we need to include that package in the final image)
Fixes #176
=> fix: lua compilation

apache/Dockerfile-alpine
The new configuration for server token / server signature was missing from the Alpine variant.
=> fix: add missing configuration to Dockerfile-alpine

README-containers.md, README.md, apache/Dockerfile, apache/Dockerfile-alpine, nginx/Dockerfile, nginx/Dockerfile-alpine
- make Lua version an ARG
- update httpd to 2.4.58
- update nginx to 1.25.3
=> chore: update dependencies

README-containers.md, README.md, docker-bake.hcl
=> chore: upgrade apache to 2.4.59

nginx/Dockerfile, nginx/Dockerfile-alpine, openresty/Dockerfile-alpine
Don't know why we oversaw this change 🤔
=> fix: use new upstream sources

apache/docker-entrypoint.sh, nginx/docker-entrypoint.d/01-check-low-port.sh, src/bin/check-low-port
- do not start container if port or ssl_port are defined lower than 1024
after moving to unprivileged containers, people might not have updated their setups, bringing problems when starting
=> chore: error if port or ssl_port are lower than 1024

docker-bake.hcl, renovate.json
Experimental support for updating versions in bake file.
=> feat: manage deps with renovate

.github/workflows/publish.yml
We are using the two branch approach when we can just stick to one main branch and just release new versions.
This should simplify generating new releases, and keep commits cleaner.
=> chore: create a new release when we... release

src/etc/modsecurity.d/modsecurity.conf
The new modsecurity.conf file was missing rule 200001, which enables body processing of `application/json`.
Also took the opportunity to put the content of the file into a form that is easier to maintain w.r.t. to changes from upstream.
Fixes #252
=> fix: add missing JSON Content-Type rule

src/bin/check-low-port
The container did not start anymore on the latest build. The logs didn't really tell what was going on, because the message from the check-low-port script is not printed. Heredoc needs to go through `cat`, not `echo`.
=> Fix heredoc in check-low-port

.github/workflows/verifyimage.yml
We didn't move the branches when renaming.
=> fix: use correct branch for tests

README.md, docker-compose.yaml, src/opt/modsecurity/activate-rules.sh
Adresses issue: https://github.com/coreruleset/modsecurity-crs-docker/issues/256
=> fix: split restricted headers to work with crs 4.2

apache/Dockerfile, apache/Dockerfile-alpine
Following #227, http user cannot read or write /tmp/modsecurity. Added /tmp/modsecurity to the list of directories owned by httpd.
This fixes #262
=> Fix permissions on /tmp/modsecurity directory on Apache image

renovate.json
- run renovate daily
- catch updates faster on CRS, upstream changes and more.
=> chore: run renovate daily to quickly catch updates

README.md
missing \ in example command in README.md
=> missing \ in example command in README.md

README.md
Corrects `fromat` to `format` in the `README.md`.
=> Correct a small typo in the README.md

apache/Dockerfile, apache/Dockerfile-alpine, nginx/Dockerfile, nginx/Dockerfile-alpine, openresty/Dockerfile-alpine
- switch from full release to minimal
- use same curl call everywhere
- prevent from being blocked in Azure
Fixes #284.
=> fix: use crs minimal in docker images

nginx/Dockerfile, nginx/Dockerfile-alpine, openresty/Dockerfile-alpine
Removed geo-ip flag and library to ensure proper functionality based upon "nginx -s reload" based on Issue 2041 (Modsecurity)
=> fix: modify Nginx Dockerfile to address OWASP ModSecurity Issue #2041

.github/workflows/verifyimage.yml, src/etc/modsecurity.d/modsecurity.conf
This update replaces the fixed value `1000` in the `SecRule` with the `${MODSEC_ARGUMENTS_LIMIT}` variable within the `src/etc/modsecurity.d/modsecurity.conf` file.
- **Centralized Configuration**: Utilizing `${MODSEC_ARGUMENTS_LIMIT}` centralizes the configuration of the argument limit, simplifying future adjustments and ensuring consistency across the configuration files.
- **Alignment with Documentation**: According to the [ModSecurity Reference Manual](https://github.com/owasp-modsecurity/ModSecurity/wiki/Reference-Manual-%28v3.x%29#secargumentslimit), it's recommended to pair the `SecArgumentsLimit` directive with a corresponding rule. This prevents attackers from bypassing the limit by adding additional parameters beyond the set threshold.
- **Modified File**: …
=> fix: use MODSEC_ARGUMENTS_LIMIT in SecRule for argument count limit

openresty/Dockerfile-alpine
Hello,
We've noticed these errors in the logs:
```
[173049359014.027868] [/private/api/v1/fileUpload] [1] Multipart: Failed to create file: /tmp/modsecurity/upload/20241101-203950-173049359014.027868-file-XXXXXX
[173049359014.027868] [/private/api/v1/fileUpload] [1] Multipart: Final boundary missing.
```
The important bit is `Multipart: Failed to create file`, while `Multipart: Final boundary missing` is the consequence of that and is not the cause, but the effect of the issue.
This PR changes the ownership on /tmp/modsecurity from root:root to nobody:nobody recursively, so nginx workers running under that user can write to the directories within /tmp/modsecurity.
=> Fix /tmp/modsecurity/* directories permissions so nginx workers can write to them

README.md, nginx/Dockerfile, nginx/Dockerfile-alpine, nginx/templates/conf.d/default.conf.template, nginx/templates/includes/cors.conf.template, nginx/templates/nginx.conf.template
- add cors hedaers to the 403 answer
Fixes #112
=> feat: add cors headers default nginx

README.md, nginx/templates/conf.d/default.conf.template, nginx/templates/nginx.conf.template
The ngx_http_headers_more_filter_module isn't shipped in the upstream image, which currently breaks our images when nginx tries to load the module at startup.
Fixes #306
=> fix: deactivate use of missing module

README.md
=> docs: document REPORTING_LEVEL

.github/workflows/verifyimage.yml, README.md, docker-bake.hcl, nginx/Dockerfile, nginx/Dockerfile-alpine, nginx/templates/conf.d/default.conf.template, nginx/templates/includes/cors.conf.template, nginx/templates/nginx.conf.template
- compile header_more modules
- fix cors
=> fix: nginx module more headers

README.md
The default value for ALLOWED_REQUEST_CONTENT_TYPE shown in README.md doesn't match the actual default value in CRS, which is misleading if you try to customize the setting by following the example. This PR corrects that.
=> docs: fix default value for ALLOWED_REQUEST_CONTENT_TYPE

.github/workflows/configure-rules-for-test.sh, .github/workflows/verifyimage.yml, src/opt/modsecurity/configure-rules.conf
This PR fixes #320 and corrects the variable names ANOMALY_INBOUND and ANOMALY_OUTBOUND.
=> fix: set correct variable names for ANOMALY_INBOUND and OUTBOUND

docker-bake.hcl, nginx/Dockerfile, nginx/Dockerfile-alpine
=> use stable version of modsecurity nginx connector

nginx/templates/conf.d/default.conf.template, nginx/templates/includes/proxy_backend.conf.template
`proxy_pass` will use the resolver whenever the argument contains variables. This isn't usually an issue but it can be if hosts are declared via `/etc/hosts`, e.g. when useing `extra_hosts` from docker compose. Then, `/etc/hosts` would not be considered.
Use the `BACKEND` variable directly to avoid use of the resolver.
Fixes #330
=> fix: replace `$upstream` variable with `BACKEND` env var

README.md, docker-bake.hcl, renovate.json
closes: #336 
Nginx’s stable branch is recommended for production, but Renovate is currently tracking the mainline (1.27.x) releases. 
We need to restrict updates to stable versions to follow best practices and ensure reliability.
Updated `renovate.json` to add `allowedVersions` using a regex that matches only stable (even minor) versions of `nginxinc/nginx-unprivileged`.
This ensures Renovate will not propose mainline updates (e.g., 1.27.x).
Ran a local dry-run (`LOG_LEVEL=debug npx renovate --platform=local --repository-cache=reset --dry-run`) and confirmed that only stable patch updates (e.g., 1.26.3) are picked up.
```
❯ node -v
v22.13.1
❯ npx renovate --version
39.176.4
❯ gsed -z -i 's/    "local>coreruleset\/renovate-config",\n//g' renovate.json   
❯ LOG_LEVEL=debug npx renovate …
```
=> fix: Add allowedVersions to restrict Nginx to stable releases

apache/Dockerfile, apache/Dockerfile-alpine, docker-bake.hcl, nginx/Dockerfile, nginx/Dockerfile-alpine, nginx/docker-entrypoint.d/0-move-writables.sh
=> feat: enable running nginx containers with read-only root fs

nginx/Dockerfile-alpine
See https://github.com/owasp-modsecurity/ModSecurity-nginx/pull/275. ModSecurity-nginx uses `printf` as part of the nginx configure test. As of GCC 14, this leads to an error during compilation and thus to an error when running `configure` on nginx.
This commit works around the issue by patching the `config` file in ModSecurity-nginx with a valid value for.
This affects the nginx-alpine build as of nginx 1.28.0 which is built with Alpine 3.21, which requires GCC 14+.
=> fix: work around configure issue with GCC 14+

README.md
This pull request corrects several typos and improves the overall spelling in the README.md file.
- Fixed minor spelling mistakes and improved clarity in a few sentences.
- No changes were made to the functionality or technical content.
=> Fix typos and improve spelling in README.md

.github/workflows/verifyimage.yml, README.md, apache/Dockerfile, apache/Dockerfile-alpine, apache/conf/extra/httpd-vhosts.conf, docker-compose.yaml, nginx/Dockerfile, nginx/Dockerfile-alpine, nginx/templates/nginx.conf.template
- add explicit HTTP/2 configuration to nginx
- add `h2c` to default protocols for httpd
- add `H2Direct` directive and configuration option to httpd
=> feat: improve HTTP/2 configuration

docker-bake.hcl
Certain packages are no longer available for 32-bit ARM, libcurl3-gnutls for Debian specifically.
We choose to drop support for 32-bit ARM instead of investing time to find a workaround.
=> fix: drop support for 32-bit ARM (arm/v7)

README.md
- remove unsupported platforms
- remove dockeri.co image as the service is gone
- cleanup
=> docs: update readme platforms
