src/docker-entrypoint.sh

Adds quoting to entrypoint shell script

---

.github/workflows/buildimage.yml

Fixed the workflow as there was a problem during the build

Fix pipeline

---

.github/workflows/buildimage.yml

Adds action to push readme to docker hub.
Solves #18.

fix(docs): add github action to update readme on dockerhub

---

.github/workflows/buildimage.yml
.github/workflows/dockerhub-description.yml

Move README update to independent workflow.

fix(readme): create a new workflow for updating readme

---

Makefile

Noticed a typo in the Makefile and fixed it.

Fix typo for addsuffix in Makefile

---

docker-bake.hcl

feat(ci): cleanup and simplify docker bake

---

.github/workflows/buildimage.yml

Adds an endpoint for rebuilding when base container changes.

feat(ci): add repository dispatch for rebuilding

---

README.md
src/opt/modsecurity/activate-rules.sh

Added documentation on ENABLE_CRS_TEST_MARKER to readme
Use brace notation for variables in shell script

Added environment variable for writing CRS test marker rule to crs-setup.conf

---

nginx/docker-entrypoint.sh

Adds new file to be processed by env subst.
Fixes https://github.com/coreruleset/modsecurity-docker/issues/107

fix(nginx): match with changes upstream

---

apache/Dockerfile
apache/Dockerfile-alpine
nginx/Dockerfile
nginx/Dockerfile-alpine

- adds gpg release verification
- splits build in release get and config files copying

feat(gpg): add release signature verification

---

.github/workflows/buildimage.yml
.github/workflows/verifyimage.yml
README.md
apache/Dockerfile
apache/Dockerfile-alpine
docker-bake.hcl
nginx/Dockerfile
nginx/Dockerfile-alpine

chore: release tag changes

---

README.md
apache/Dockerfile
apache/Dockerfile-alpine
apache/conf/extra/httpd-locations.conf
apache/conf/extra/httpd-modsecurity.conf
apache/conf/extra/httpd-ssl.conf
apache/conf/extra/httpd-vhosts.conf
apache/openssl.conf
docker-bake.hcl
nginx/Dockerfile
nginx/Dockerfile-alpine
nginx/docker-entrypoint.d/90-copy-modsecurity-config.sh
nginx/docker-entrypoint.d/91-update-resolver.sh
nginx/docker-entrypoint.d/92-update-real_ip.sh
nginx/openssl.conf
nginx/templates/conf.d/default.conf.template
nginx/templates/conf.d/logging.conf.template
nginx/templates/conf.d/modsecurity.conf.template
nginx/templates/includes/location_common.conf.template
nginx/templates/includes/proxy_backend.conf.template
nginx/templates/nginx.conf.template
src/bin/healthcheck
src/etc/modsecurity.d/modsecurity-override.conf

Merge with base container

---

README.md

fix: update slack invitation link in readme

---

.github/workflows/buildimage.yml
.github/workflows/verifyimage.yml
apache/Dockerfile
apache/Dockerfile-alpine

Follow up after new modsecurity release.

feat(apache): update modsecurity to v2.9.7

---

.github/workflows/lint.yml
README-containers.md

Trimmed down version of the readme document.
Fixes #122.

docs: create specific file for dockerhub

---

README.md

Update RESTRICTED_HEADERS default value

---

nginx/Dockerfile-alpine

New modsecurity v3 version out

feat: upgrade modsecurity to v3.0.9

---

nginx/Dockerfile
nginx/Dockerfile-alpine

- Update modsecurity nginx version to 3.0.11.

Update modsecurity 3.0.11

---

apache/Dockerfile
apache/Dockerfile-alpine
nginx/Dockerfile
nginx/Dockerfile-alpine
nginx/templates/nginx.conf.template

Use unprivileged images and always run images as non-root.
Fixes #55

feat: use nginx-unprivileged images

---

docker-bake.hcl

feat: update modsecurity to 3.0.12

---

.github/workflows/publish.yml
.github/workflows/verifyimage.yml
docker-bake.hcl

- add cosign to sign images
- per https://docs.docker.com/build/ci/github-actions/push-multi-registries/, just using the proper tags should push to both registries so we don't need to build twice
Fixes #96

feat: add cosign

---

README-containers.md
README.md
REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
docker-bake.hcl

- update CRS to v4.0.0
- update project name to OWASP CRS

feat: update CRS to v4.0.0

---

README-containers.md
README.md

docs: update docs to reflect changes to PROXY_SSL* vars

---

docker-compose.yaml

docker-compose 3.7 with x-defaults

---

openresty/docker-entrypoint.d/93-update-proxy-ssl-config.sh
openresty/templates/includes/location_common.conf.template

Add `/healthz` endpoint. Might fix #219.

fix(openresty): add healthz endpoint

---

.github/workflows/verifyimage.yml

- break the build if the file has changed
- we need to upgrade our own build before continuing

chore: check modsecurity.conf-recommended has not changed

---

nginx/Dockerfile
nginx/Dockerfile-alpine
openresty/Dockerfile-alpine

Added maximDB support to dockerfile for OWASP CRS 4.5 Nginx Image

Updated Nginx Dockerfile for MaximDB support

---

.github/workflows/verifyimage.yml
src/etc/modsecurity.d/modsecurity.conf

File was updates upstream in https://github.com/owasp-modsecurity/ModSecurity/commit/63201ae39f49f55b166e72f9e46dd7bfe86f7874

fix: update upstream modsecurity.conf-recommended

---

README.md
docker-bake.hcl

Also update docs to include the new image variants

fix: use correct tags for read-only images

---

.github/workflows/configure-rules-for-test.sh
.github/workflows/verifyimage.yml
apache/Dockerfile
apache/Dockerfile-alpine
docker-bake.hcl
nginx/Dockerfile
nginx/Dockerfile-alpine

Use pcre2 for building on apache

feat(apache): switch to pcre2

---

README.md

docs: update buildx targets

---

.github/workflows/lint.yml
.github/workflows/publish.yml
.github/workflows/verifyimage.yml
renovate.json

- update and upgrade gha pinned versions
- keep actions up to date and secure

ci: update pinned verions

---

apache/Dockerfile
apache/Dockerfile-alpine
nginx/Dockerfile
nginx/Dockerfile-alpine

- skip warnings
- cleaner build
- https://docs.docker.com/build/checks/

fix: skip docker warnings

---

.github/workflows/publish.yml
.github/workflows/verifyimage.yml

- update deprecated bake subaction
- fix warning
- #378

chore: update bake matrix subaction
